// <auto-generated />
using System;
using FengshuiChecker.Console.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FengshuiChecker.Migrations
{
    [DbContext(typeof(FengshuiCheckerDbContext))]
    [Migration("20220415030259_RenameFengshuiTypeColumn")]
    partial class RenameFengshuiTypeColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FengshuiChecker.Console.Models.PhoneNetworkProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhoneNetworkProviders");
                });

            modelBuilder.Entity("FengshuiChecker.Console.Models.PhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PhoneNumberPrefixId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumberPrefixId");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("FengshuiChecker.Console.Models.PhoneNumberPrefix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFengshuiPrefix")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PhoneNetworkProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNetworkProviderId");

                    b.ToTable("PhoneNumberPrefixes");
                });

            modelBuilder.Entity("FengshuiChecker.Console.Models.PhoneNumber", b =>
                {
                    b.HasOne("FengshuiChecker.Console.Models.PhoneNumberPrefix", "PhoneNumberPrefix")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PhoneNumberPrefixId");

                    b.Navigation("PhoneNumberPrefix");
                });

            modelBuilder.Entity("FengshuiChecker.Console.Models.PhoneNumberPrefix", b =>
                {
                    b.HasOne("FengshuiChecker.Console.Models.PhoneNetworkProvider", null)
                        .WithMany("PhoneNumberPrefixes")
                        .HasForeignKey("PhoneNetworkProviderId");
                });

            modelBuilder.Entity("FengshuiChecker.Console.Models.PhoneNetworkProvider", b =>
                {
                    b.Navigation("PhoneNumberPrefixes");
                });

            modelBuilder.Entity("FengshuiChecker.Console.Models.PhoneNumberPrefix", b =>
                {
                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
